# Generated by Django 4.0.4 on 2022-05-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категорія страви')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL категорії')),
            ],
            options={
                'verbose_name': 'Категорія страви',
                'verbose_name_plural': 'Категорії страв',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Страва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL страви')),
                ('composition', models.TextField(verbose_name='Склад')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('price', models.IntegerField(verbose_name='Ціна')),
            ],
            options={
                'verbose_name': 'Страва',
                'verbose_name_plural': 'Страви',
            },
        ),
    ]
