# Generated by Django 4.0.4 on 2022-05-31 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_tablereservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableReservation',
        ),
    ]
