# Generated by Django 4.0.4 on 2022-07-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_productincart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='photos/menu/', verbose_name='Фото'),
        ),
    ]
