# Generated by Django 4.0.4 on 2022-07-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_category_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='serial_number',
            field=models.IntegerField(unique=True, verbose_name='Порядковий номер'),
        ),
    ]
