# Generated by Django 4.0.4 on 2022-07-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_category_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='serial_number',
            field=models.IntegerField(verbose_name='Порядковий номер'),
        ),
    ]
