# Generated by Django 4.0.4 on 2022-06-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name="Ім'я клієтна")),
                ('client_phone_number', models.IntegerField(verbose_name='Номер телефону')),
                ('adress', models.TextField(verbose_name='Адреса доставки')),
                ('time_delivery', models.TimeField(verbose_name='Час доставки')),
                ('order', models.TextField(verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
        migrations.CreateModel(
            name='TakeAway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name="Ім'я клієтна")),
                ('client_phone_number', models.IntegerField(verbose_name='Номер телефону')),
                ('time_cooking', models.TimeField(verbose_name='Час приготування')),
                ('order', models.TextField(verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Самовивіз',
                'verbose_name_plural': 'Самовивози',
            },
        ),
        migrations.RemoveField(
            model_name='tablereservation',
            name='special_requests',
        ),
    ]
