# Generated by Django 4.0.4 on 2022-06-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_delivery_takeaway_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablereservation',
            options={'verbose_name': 'Бронювання столу', 'verbose_name_plural': 'Бронювання столиків'},
        ),
    ]
