# Generated by Django 4.0.4 on 2022-06-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_delivery_order_remove_tablereservation_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order_comment',
            field=models.TextField(verbose_name='Коментар до замовлення'),
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='order_comment',
            field=models.TextField(verbose_name='Коментар до замовлення'),
        ),
    ]
