# Generated by Django 4.0.4 on 2022-06-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_delivery_order_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='date_reservation',
            field=models.IntegerField(default=0, verbose_name='Дата бронювання'),
        ),
    ]
