# Generated by Django 4.0.4 on 2022-06-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_tablereservation_date_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='date_reservation',
            field=models.IntegerField(default=24.6, verbose_name='Дата бронювання'),
        ),
    ]
