# Generated by Django 4.0.4 on 2022-06-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_tablereservation_date_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='amount_persons',
            field=models.TextField(verbose_name='Кількість персон'),
        ),
    ]
