# Generated by Django 4.0.4 on 2022-06-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_tablereservation_amount_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='date_reservation',
            field=models.FloatField(verbose_name='Дата бронювання'),
        ),
    ]
