# Generated by Django 4.0.4 on 2022-06-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_tablereservation_date_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='amount_persons',
            field=models.IntegerField(verbose_name='Кількість персон'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='date_reservation',
            field=models.CharField(max_length=5, verbose_name='Дата бронювання'),
        ),
    ]
