# Generated by Django 4.0.4 on 2022-06-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_tablereservation_amount_persons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='date_reservation',
            field=models.CharField(max_length=255, verbose_name='Дата бронювання'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='time_reservation',
            field=models.TimeField(max_length=255, verbose_name='Час бронювання'),
        ),
    ]
