# Generated by Django 4.0.4 on 2022-06-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_tablereservation_date_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='date_reservation',
            field=models.DateField(max_length=255, verbose_name='Дата бронювання'),
        ),
    ]
