# Generated by Django 4.0.4 on 2022-06-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_tablereservation_date_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='client_phone_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='client_phone_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='date_reservation',
            field=models.DateField(max_length=255, verbose_name='Дата бронювання'),
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='client_phone_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефону'),
        ),
    ]
