# Generated by Django 4.0.4 on 2022-07-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_delivery_client_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='order',
            field=models.TextField(default='Замовлення в закладі', verbose_name='Замовлення'),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Вартість замовлення'),
        ),
        migrations.AddField(
            model_name='takeaway',
            name='order',
            field=models.TextField(default='-', verbose_name='Замовлення'),
        ),
        migrations.AddField(
            model_name='takeaway',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Вартість замовлення'),
        ),
    ]
