# Generated by Django 4.0.4 on 2022-07-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_delete_delivery_tablereservation_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeaway',
            name='order',
            field=models.TextField(verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='total_price',
            field=models.IntegerField(verbose_name='Вартість замовлення'),
        ),
    ]
