# Generated by Django 4.0.4 on 2022-07-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_tablereservation_reason_for_cancel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='reason_for_cancel',
            field=models.TextField(blank=True, default='-', verbose_name='Причина скасування'),
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='reason_for_cancel',
            field=models.TextField(blank=True, default='-', verbose_name='Причина скасування'),
        ),
    ]
