# Generated by Django 4.0.4 on 2022-07-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminadditionalinfo',
            options={'verbose_name': 'Інформація про адмінстратора', 'verbose_name_plural': 'Інформація про адмінстраторів'},
        ),
        migrations.AlterField(
            model_name='adminadditionalinfo',
            name='rigths',
            field=models.CharField(choices=[('order_management', 'Керування замовленнями'), ('menu_editing', 'Редагування меню'), ('all_rights', 'Повні права')], max_length=255, verbose_name='Права'),
        ),
    ]
