# Generated by Django 4.0.4 on 2022-08-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0003_rename_rigths_adminadditionalinfo_rights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminadditionalinfo',
            name='rights',
            field=models.CharField(choices=[('order_management', 'Керування замовленнями'), ('menu_editing', 'Редагування меню'), ('rest_info_editing', 'Редагування інфо про ресторан'), ('all_rights', 'Повні права')], max_length=255, verbose_name='Права'),
        ),
    ]
