# Generated by Django 4.0.4 on 2022-06-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_email', models.EmailField(max_length=254, verbose_name='Електронна адреса ресторану')),
                ('rest_phone_number', models.IntegerField(verbose_name='Номер телефону ресторану')),
                ('time_working', models.CharField(max_length=255, verbose_name='Час роботи')),
            ],
            options={
                'verbose_name': 'Інформація про ресторан',
                'verbose_name_plural': 'Інформація про ресторан',
            },
        ),
    ]
