# Generated by Django 4.0.4 on 2022-06-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_user', '0002_remove_restaurantinfo_rest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/slider', verbose_name='Зображення для слайдера')),
            ],
            options={
                'verbose_name': 'Контент слайдера',
                'verbose_name_plural': 'Контент слайдера',
            },
        ),
    ]
