# Generated by Django 4.0.4 on 2022-06-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_user', '0003_slidercontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidercontent',
            name='slide_name',
            field=models.CharField(max_length=255, verbose_name="Ім'я слайдера"),
        ),
    ]
