# Generated by Django 4.0.4 on 2022-08-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_user', '0004_alter_slidercontent_slide_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='about_restaurant',
            field=models.TextField(default='-', verbose_name='Про ресторан'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='main_page_video',
            field=models.FileField(default='-', upload_to='videos/', verbose_name='Відео для головної сторінки'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='wifi_name',
            field=models.CharField(default='-', max_length=255, verbose_name='Wi-Fi'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='wifi_passsword',
            field=models.CharField(default='-', max_length=255, verbose_name='Пароль Wi-Fi'),
        ),
    ]
